// Seed 500 jokes directly to the database via Prisma
// Run: cd ~/Desktop/jokehub && node seed-500.mjs

const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

const J = [
// ── Dad Jokes & One-liners (varied sources) ──
["I went to buy some camo pants but couldn't find any.","CamoCarl","dad jokes"],
["I failed math so many times at school, I can't even count.","MathDropout","school,dad jokes"],
["I used to have a handle on life, but then it broke.","BrokenBill","dad jokes"],
["My wife told me to stop impersonating a flamingo. I had to put my foot down.","FlamingoPhil","marriage,dad jokes"],
["I stayed up all night wondering where the sun went. Then it dawned on me.","SleepySteve","science,dad jokes"],
["I have a fear of speed bumps, but I'm slowly getting over it.","CautiousCarl","dad jokes"],
["Communist jokes aren't funny unless everyone gets them.","PolPundit","dad jokes"],
["Geology rocks, but geography's where it's at.","RockHound","science,school"],
["My friend's bakery burned down last night. Now his business is toast.","BakerBob","food,dad jokes"],
["Four fonts walk into a bar. The bartender says: We don't want your type in here.","TypeFace","dad jokes"],
["If you don't pay your exorcist, do you get repossessed?","GhostGuy","dad jokes"],
["I bought the world's worst thesaurus. Not only is it terrible, it's also terrible.","WordNerd","dad jokes"],
["A ghost walked into a bar and ordered a shot of vodka. The bartender said: Sorry, we don't serve spirits here.","BarFly","food,dad jokes"],
["The man who invented knock-knock jokes should get a no bell prize.","DoormanDan","dad jokes"],
["I can't stand Russian dolls. They're so full of themselves.","MatryoshkaMike","dad jokes"],
["I told my Wi-Fi we needed space. It disconnected.","TechTrouble","programming,dad jokes"],
["I stayed up all night to see where the sun went, and then it dawned on me.","AstroAlex","science,dad jokes"],
["I'm friends with all electricians. They're very current.","SparkyStan","work,dad jokes"],
["I was going to tell a roof joke, but it's over your head.","RooferRick","work,dad jokes"],
["I asked the gym instructor if he could teach me to do the splits. He said: How flexible are you? I said: I can't make Tuesdays.","GymGary","sports,dad jokes"],
// ── Clean Jokes ──
["What did one eye say to the other? Between you and me, something smells.","OptometristOllie","doctors,dad jokes"],
["Why are snowmen so easy to get along with? Because they're very chill.","FrostyFiona","kids,dad jokes"],
["Why do vampires use breath mints? Because they have bat breath.","VampireVic","kids,dad jokes"],
["Why did the rabbit go to the salon? It was having a bad hare day.","BunnyBeatrice","animals,dad jokes"],
["I'm on a seafood diet. When I see food, I eat it.","FoodiePhil","food,dad jokes"],
["Why did the invisible man quit his job? He just couldn't see himself doing it.","InvisibleIvan","work,dad jokes"],
["What did the credit card say after being arrested? Guilty as charged.","BankerBetty","dad jokes"],
["Why can't you surprise mountains? Because they're always peaking.","HikerHank","dad jokes"],
["Did you hear the one about the peach? It's pitiful.","FruitFrank","food,dad jokes"],
["Why are mummies short-tempered? Because they're all wound up.","ArcheoAnna","kids,dad jokes"],
["Did you hear about the cow that couldn't produce milk? It was an udder disaster.","FarmerFaye","animals,dad jokes"],
["What one word does everyone pronounce wrong? Wrong.","GrammarGrace","school,dad jokes"],
["Why can't leopards hide? They're always spotted.","JungleJane","animals,kids"],
["How much do dead batteries cost? Nothing. They're free of charge.","ElectricEd","science,dad jokes"],
["Why are owls so carefree? Because they don't give a hoot.","BirdBrain","animals,dad jokes"],
["When is a door not a door? When it's ajar.","PhilosoFred","dad jokes"],
["Why did the pony need a glass of water? Because it was feeling a little horse.","StableSam","animals,dad jokes"],
["Where do armies go? Into your sleevies.","MilitaryMike","kids,dad jokes"],
// ── Puns & Wordplay ──
["I did a theatrical performance about puns. It was really just a play on words.","TheatreTom","dad jokes"],
["Why did the can crusher quit her job? It was soda-pressing.","RecycleRita","work,dad jokes"],
["Why do people love Switzerland? Well, the flag is a big plus.","TravelTrish","dad jokes"],
["Becoming vegetarian was a huge missed steak.","VeggieVera","food,dad jokes"],
["I don't enjoy computer jokes. Not one bit.","ByteBen","programming,dad jokes"],
["I changed my phone's name to Titanic. It's syncing now.","SailorSue","dad jokes"],
["Jokes about German sausage are the wurst.","BratwurstBill","food,dad jokes"],
["I got a job at a bakery because I kneaded dough.","DoughDave","food,work"],
["Why is Peter Pan always flying? He Neverlands.","FairytaleFern","kids,dad jokes"],
["What do you call a broken can opener? A can't opener.","HandyHelen","dad jokes"],
["How do trees feel in the Spring? Releaved.","TreeTerry","science,dad jokes"],
["I refuse to work with compost. It's degrading.","GardenGail","work,dad jokes"],
["Why aren't depressed people worried about flat tires? They're always carrying despair.","TireTina","dad jokes"],
// ── Animals ──
["What do you call a sleeping bull? A bulldozer.","CowboyChris","animals,dad jokes"],
["Why don't cows have money? Because the farmers milk them dry.","DairyDan","animals,dad jokes"],
["What do you call a fish that wears a bowtie? Sofishticated.","AquaAlex","animals,dad jokes"],
["Why do seagulls fly over the sea? Because if they flew over the bay, they'd be bagels.","BeachBabe","animals,food"],
["What do you get when you cross a snowman with a vampire? Frostbite.","WinterWill","animals,kids"],
["Why do cows wear bells? Because their horns don't work.","BellBoy","animals,dad jokes"],
["What do you call a lazy kangaroo? A pouch potato.","AussieAdam","animals,dad jokes"],
["Why do fish live in salt water? Because pepper makes them sneeze.","MarineMary","animals,kids"],
["What do you call a dog that does magic? A Labracadabrador.","MagicMutt","animals,kids"],
["Why don't oysters share? Because they're shellfish.","PearlPat","animals,food"],
["What do you call a group of disorganized cats? A cat-astrophe.","CatLadyCleo","animals,dad jokes"],
["Why do hummingbirds hum? Because they don't know the words.","BirdyBill","animals,kids"],
["What do you get when you cross a sheep and a bee? A bah-humbug.","ChristmasChuck","animals,kids"],
["What's a cat's favorite dessert? Mice cream.","KittyKate","animals,food"],
// ── Work & Office ──
["My boss told me to have a good day. So I went home.","OfficeOliver","work,dad jokes"],
["I got a new job crushing cans. It's soda pressing.","CanCrusher","work,dad jokes"],
["I told my boss three companies were after me so I needed a raise. He asked which three. I said gas, electric, and water.","SavvySarah","work,dad jokes"],
["I always arrive late to the office, but I make up for it by leaving early.","SlackerStan","work,dad jokes"],
["The first five days after the weekend are always the hardest.","MondayMike","work,dad jokes"],
["My resumé is just a list of things I hope you never verify.","CVChris","work,dad jokes"],
["I like my job. It's the work I hate.","PhilosoWorker","work,dad jokes"],
["My boss asked me to start the presentation with a joke. So I put my paycheck on the first slide.","PresentPete","work,dad jokes"],
// ── Science & Tech ──
["There are only 10 types of people in the world: those who understand binary and those who don't.","BinaryBob","programming,science"],
["A SQL query walks into a bar, sees two tables and asks: Can I join you?","QueryQuinn","programming,dad jokes"],
["Why do programmers prefer dark mode? Because light attracts bugs.","DarkModeDan","programming,dad jokes"],
["How do you comfort a JavaScript bug? You console it.","JSJenny","programming,dad jokes"],
["The best thing about UDP jokes is I don't care if you get them.","NetworkNate","programming,dad jokes"],
["Why was the computer cold? It left its Windows open.","WindowsWill","programming,dad jokes"],
["What's a computer's least favorite food? Spam.","SpamSam","programming,food"],
["Why did the PowerPoint presentation cross the road? To get to the other slide.","SlideSally","programming,work"],
["A photon checks into a hotel. The bellhop asks: Can I help you with your luggage? The photon replies: No thanks, I'm traveling light.","PhotonPete","science,dad jokes"],
["What did the biologist wear on his first date? Designer genes.","BioBlake","science,dad jokes"],
["Why can't you trust an atom? They make up literally everything.","AtomAmy","science,dad jokes"],
// ── Food ──
["I'm on a whiskey diet. I've lost three days already.","WhiskeyWalt","food,dad jokes"],
["What did the sushi say to the bee? Wasabee.","SushiStan","food,dad jokes"],
["Why did the banana go to the doctor? It wasn't peeling well.","BananaBob","food,doctors"],
["What do you call a sad strawberry? A blueberry.","BerryBeth","food,kids"],
["I would tell you a pizza joke, but it's probably too cheesy.","PizzaPaul","food,dad jokes"],
["Why did the yogurt go to the art exhibition? Because it was cultured.","YogurtYvette","food,dad jokes"],
["What did the grape say when it got stepped on? Nothing, it just let out a little wine.","GrapeGina","food,dad jokes"],
["How do you make a lemon drop? Just let it fall.","LemonLarry","food,dad jokes"],
["What do you call a fake noodle? An impasta.","PastaPatrick","food,dad jokes"],
// ── Marriage & Family ──
["Marriage is like a deck of cards. In the beginning all you need is two hearts and a diamond. By the end, you wish you had a club and a spade.","MarriedMarvin","marriage,dad jokes"],
["My wife says I only have two faults: I don't listen and something else.","DeafDad","marriage,dad jokes"],
["I asked my wife what she wanted for her birthday. She said: Nothing would make me happier than a diamond necklace. So I got her nothing.","CheapCharlie","marriage,dad jokes"],
["Behind every great man, there's a woman rolling her eyes.","EyeRollEmma","marriage,dad jokes"],
["My wife told me I was one in a million. When I checked, she was right.","StatsStu","marriage,dad jokes"],
// ── School ──
["Why did the student eat his homework? Because his teacher told him it was a piece of cake.","StudentStan","school,kids"],
["What's a math teacher's favorite season? Sum-mer.","MathTeacherMel","school,dad jokes"],
["Why did the music teacher need a ladder? To reach the high notes.","MusicMiss","school,dad jokes"],
["What do you call a dinosaur that crashes their car? Tyrannosaurus wrecks.","DinoDerek","school,kids"],
["Why was the geometry book always so stressed? It had too many problems.","GeometryGuy","school,science"],
// ── Sports ──
["Why did the golfer bring two pairs of pants? In case he got a hole in one.","GolferGreg","sports,dad jokes"],
["Why can't Cinderella play soccer? Because she keeps running away from the ball.","SoccerSophie","sports,kids"],
["What lights up a soccer stadium? A soccer match.","MatchMaker","sports,dad jokes"],
["Why do tennis players never get married? Because love means nothing to them.","TennisTom","sports,dad jokes"],
["What's a boxer's favorite drink? Punch.","BoxerBen","sports,food"],
// ── Kids ──
["What do you call a dinosaur that is sleeping? A dino-snore.","DinoKid","kids,animals"],
["Why did the teddy bear say no to dessert? Because she was already stuffed.","TeddyTina","kids,food"],
["What has ears but can't hear? A cornfield.","CornKid","kids,dad jokes"],
["What do you call a boomerang that won't come back? A stick.","BoomerangBoy","kids,dad jokes"],
["Why did the cookie go to the doctor? Because it was feeling crummy.","CookieKid","kids,food"],
["What animal is always at a baseball game? A bat.","BaseballBoy","kids,sports"],
["What falls in winter but never gets hurt? Snow.","SnowKid","kids,dad jokes"],
["How does the moon cut his hair? Eclipse it.","MoonKid","kids,science"],
["What do you call a train that sneezes? Achoo-choo train.","TrainKid","kids,dad jokes"],
["Why are ghosts bad liars? Because you can see right through them.","GhostKid","kids,dad jokes"],
// ── Doctors ──
["Why did the doctor carry a red pen? In case he needed to draw blood.","NurseNancy","doctors,dad jokes"],
["What do you call a doctor who fixes websites? A URLologist.","WebDoc","doctors,programming"],
["Patient: Doctor, I broke my arm in two places. Doctor: Well, stop going to those places.","DrComedy","doctors,dad jokes"],
["Why did the germ cross the microscope? To get to the other slide.","LabLisa","doctors,science"],
["I went to the doctor and told him I broke my arm in two places. He told me to stop going to those places.","ClumyCarl","doctors,dad jokes"],
// ── More Dad Jokes ──
["I have an inferiority complex, but it's not a very good one.","InsecureIvan","dad jokes"],
["Our vacuum cleaner is getting old. It's just gathering dust.","DustDevil","dad jokes"],
["Why did the thief take a shower before robbing the bank? He wanted to make a clean getaway.","CleanCriminal","dad jokes"],
["Getting paid to sleep would be my dream job.","SleepySam","work,dad jokes"],
["I used to be a banker, but I lost interest.","ExBanker","work,dad jokes"],
["Why did the tomato blush? It saw the salad dressing.","TomatoTim","food,dad jokes"],
["Why couldn't the toilet paper cross the road? It got stuck in a crack.","TPTony","dad jokes"],
["What do you get from a pampered cow? Spoiled milk.","PamperedPaul","animals,food"],
["Why didn't the sun go to college? It already had a million degrees.","SunnyDave","science,school"],
["What do you call someone who can't stick to a diet? A desserter.","DietDiana","food,dad jokes"],
["Why did the little strawberry cry? His mom was in a jam.","JamJimmy","food,kids"],
["Why did the belt get arrested? It held up a pair of pants.","FashionPolice","dad jokes"],
["Did you hear about the guy who drank invisible ink? He's at the hospital waiting to be seen.","InkIvan","doctors,dad jokes"],
["Why are libraries so tall? Because they have many stories.","LibrarianLaura","school,dad jokes"],
["Why did the Energizer Bunny go to jail? He was charged with battery.","BatteryBob","dad jokes"],
["What do cats eat for breakfast? Mice Krispies.","BreakfastBuddy","animals,food"],
["Did you hear about the wig thief who escaped from prison? Police are combing the area.","WigWally","dad jokes"],
["Where do surfers go for an education? Boarding school.","SurferDude","sports,school"],
["Why did the traffic light turn red? It had to change in front of all those people.","TrafficTed","dad jokes"],
["Why do hamburgers go south for the winter? So they don't freeze their buns.","BurgerBob","food,dad jokes"],
["What do you call a hen looking at a pile of lettuce? Chicken sees a salad.","ChickenCharlie","animals,food"],
["Did you hear about the two rowboats that got into an argument? It was an oar-deal.","BoatBill","dad jokes"],
["What did the buffalo say to her son on the first day of school? Bison.","BuffaloBeth","animals,school"],
["Why do ducks have feathers on their tails? To hide their butt-quacks.","DuckyDave","animals,kids"],
["Why shouldn't you tell secrets in a cornfield? Too many ears around.","CornfieldCarl","dad jokes"],
["What kind of underpants do lawyers wear? Briefs.","LawyerLarry","work,dad jokes"],
["Why did the archeologist get fired? His career was in ruins.","ArcheoAndy","work,dad jokes"],
["What did the beach say when the tide came in? Long time no sea.","CoastalChris","dad jokes"],
["Why was the math book depressed? It had too many problems.","MathMolly","school,dad jokes"],
["I was going to tell a sodium joke, but then I thought Na.","ChemistCharlie","science,dad jokes"],
["Why are frogs good at baseball? They know how to catch fly balls.","FroggyFrank","animals,sports"],
["What's the easiest building to lift? A lighthouse.","StrongSusan","dad jokes"],
["Why do tigers have stripes? They don't want to be spotted.","TigerTom","animals,dad jokes"],
["My dad was hit on the head with a can of soda. Luckily it was a soft drink.","SodaSon","dad jokes"],
["What do you call people who sleep in their socks? Tiny.","SockSally","kids,dad jokes"],
["Why do dragons sleep during the day? So they can fight knights.","DragonDave","kids,dad jokes"],
["Are all math puns bad? No, just sum.","PunnyProfessor","science,school"],
["I got rid of my vacuum cleaner. It was just gathering dust.","VacuumVince","dad jokes"],
["I excel at sleeping. In fact, I can do it with my eyes closed.","SleepChamp","dad jokes"],
["Why shouldn't you marry a calendar? Its days are numbered.","CalendarCal","marriage,dad jokes"],
["I try not to tell dad jokes. But when I do, he thinks they're funny.","MetaDad","dad jokes"],
["What did one volcano say to the other? I lava you.","VolcanoVal","science,kids"],
["Why should you avoid artists? They tend to be sketchy.","ArtAlex","dad jokes"],
["Did you hear about the kidnapping? They woke her up.","NapNancy","kids,dad jokes"],
["My mom asked me to put the cat out. I didn't know it was on fire.","FireFighter","animals,dad jokes"],
["What do you call a pencil with two erasers? Pointless.","PencilPete","school,dad jokes"],
["When is a pool safe for diving? It deep ends.","PoolPaul","sports,dad jokes"],
["Have you ever been camping? It's in tents.","CamperCarl","dad jokes"],
["I once read a book about glue. I couldn't put it down.","GlueGuy","dad jokes"],
["Why shouldn't you eat a clock? It's too time-consuming.","ClockCathy","dad jokes"],
["Did you hear about the car with logs for wheels? It wooden go.","WoodWorker","dad jokes"],
["What did one playing card say to the other? I can't deal with you.","CardShark","dad jokes"],
["Did you hear about the broken hearing aid? Wait, what?","HearingHarry","doctors,dad jokes"],
["Why do bees have sticky hair? Because they use a honeycomb.","BeeKeeper","animals,dad jokes"],
["What happens to an illegally parked frog? It gets toad away.","ParkingPat","animals,dad jokes"],
["How does the man in the moon get his hair cut? Eclipse it.","MoonBarber","science,dad jokes"],
["Did you hear about the shepherd who drove his sheep through town? He got a ticket for making a ewe turn.","ShepherdSam","animals,dad jokes"],
["If you arrest a mime, do you have to tell him he has the right to remain silent?","MimeMark","dad jokes"],
["I used to believe that all things must pass until I got stuck behind a school bus.","BusBob","dad jokes"],
["Why do we tell actors to break a leg? Because every play has a cast.","ActorAndy","dad jokes"],
["What do you call a sleeping dinosaur? A dino-snore.","SnoringSteve","animals,kids"],
["Why don't scientists trust stairs? Because they're always up to something.","StairScientist","science,dad jokes"],
["What do you call a bear caught in the rain? A drizzly bear.","RainyRick","animals,dad jokes"],
["Why did the bicycle fall over? Because it was two-tired.","BikerBob","sports,dad jokes"],
["What's orange and sounds like a parrot? A carrot.","CarrotKid","food,kids"],
["How do you organize a space party? You planet.","PartyPlanner","science,kids"],
["What did the janitor say when he jumped out of the closet? Supplies!","JanitorJim","work,kids"],
["Why don't eggs tell jokes? They'd crack each other up.","EggHead","food,dad jokes"],
["I would avoid the sushi if I were you. It's a little fishy.","SushiSkeptic","food,dad jokes"],
["Want to hear a construction joke? I'm still working on it.","BuilderBart","work,dad jokes"],
["What do you call a factory that makes okay products? A satisfactory.","FactoryFiona","work,dad jokes"],
["What do you call an alligator in a vest? An investigator.","GatorGary","animals,dad jokes"],
["Why did the scarecrow become a successful motivational speaker? He was outstanding in his field.","MotivatorMike","work,dad jokes"],
["Two fish are in a tank. One turns to the other and says: Any idea how to drive this thing?","TankFish","animals,dad jokes"],
["Have you ever played quiet tennis? It's the same as regular tennis but without the racket.","QuietQuinn","sports,dad jokes"],
["What kind of music do mummies listen to? Wrap music.","MummyMelody","kids,dad jokes"],
["What do you call cheese that isn't yours? Nacho cheese.","NachoNick","food,dad jokes"],
["Why was the computer tired when it got home? It had a hard drive.","HardDriveHank","programming,dad jokes"],
["Why don't seagulls fly over bays? Because then they'd be bagels.","BagelBird","animals,food"],
["What do you call a pile of cats? A meowtain.","CatMountain","animals,kids"],
["Why do bananas wear sunscreen? Because they peel.","BananaSunny","food,kids"],
["What do you call a fake stone in Ireland? A sham rock.","IrishIan","dad jokes"],
["I have a joke about paper. Never mind, it's tearable.","PaperPaul","dad jokes"],
["I just watched a program about beavers. It was the best dam program I've ever seen.","BeaverBill","animals,dad jokes"],
["Why don't some couples go to the gym? Because some relationships don't work out.","FitFail","sports,marriage"],
["What did the zero say to the eight? Nice belt.","NumberNerd","science,dad jokes"],
["How do celebrities stay cool? They have many fans.","CelebChris","dad jokes"],
["Why did the stadium get hot? All the fans left.","StadiumSteve","sports,dad jokes"],
["I tried to catch fog. I mist.","FoggyFred","dad jokes"],
["What kind of tree fits in your hand? A palm tree.","TreeHugger","kids,dad jokes"],
["I told a chemistry joke once. There was no reaction.","ChemComedian","science,school"],
["What do you call a cow with no legs? Ground beef.","BeefBuddy","animals,food"],
["Why did the math teacher break up with the calculator? She felt he was just pushing her buttons.","MathRomance","school,marriage"],
["How does a penguin build its house? Igloos it together.","PenguinPete","animals,kids"],
["What do you call a belt made of watches? A waist of time.","WatchWally","dad jokes"],
["Where do boats go when they're sick? To the dock-tor.","BoatDoc","doctors,dad jokes"],
["Why did the melon jump into the lake? It wanted to be a watermelon.","MelonMike","food,kids"],
["What do you call a snowman with a six-pack? An abdominal snowman.","SnowFit","sports,kids"],
["Why was the computer stressed? It had too many tabs open.","TabTina","programming,dad jokes"],
["What do you call a man with no arms and no legs in the water? Bob.","FloatingFred","dad jokes"],
["Did you hear about the restaurant on the moon? Great food, but no atmosphere.","SpaceDiner","food,science"],
["What kind of shorts do clouds wear? Thunderwear.","CloudCarl","kids,science"],
["What do lawyers wear to court? Lawsuits.","LawyerLinda","work,dad jokes"],
["I asked a Frenchman if he played video games. He said Wii.","GamerGaston","kids,dad jokes"],
["Why did the golfer bring an extra pair of socks? In case he got a hole in one.","GolfSocks","sports,dad jokes"],
["What's a ninja's favorite type of shoes? Sneakers.","NinjaNick","kids,dad jokes"],
["What do you call an apology written in dots and dashes? Re-morse code.","MorseMark","science,dad jokes"],
["What did the grape do when it was stepped on? It let out a little wine.","WineGrape","food,dad jokes"],
["Why do mushrooms get invited to parties? Because they're fun guys.","MushroomMax","food,dad jokes"],
["I used to play piano by ear, but now I use my hands.","PianoPlayer","dad jokes"],
["My math teacher called me average. How mean.","AverageAndy","school,dad jokes"],
["I'm on a whiskey diet. I've lost three days already.","WhiskeyWonder","food,dad jokes"],
["I can't believe I got fired from the calendar factory. All I did was take a day off.","CalendarFired","work,dad jokes"],
["My bed is a magical place. I suddenly remember everything I had to do.","BedBuddy","dad jokes"],
["I told my phone a joke but it didn't laugh. Bad reception.","PhoneFail","programming,dad jokes"],
["I tried to photograph fog but I mist the moment.","FogPhotog","dad jokes"],
["The calendar's days are numbered.","CountdownCarl","dad jokes"],
["The bakery's best joke is rolling with laughter.","BakeryBill","food,dad jokes"],
["Why was the computer cold? It left its Windows open.","ColdComputer","programming,dad jokes"],
["My socks always stick together. They're sole mates.","SockMate","dad jokes"],
["Why don't calendars get lost? They always know the date.","DateKeeper","dad jokes"],
["The pizza couldn't play cards because it was too cheesy.","PizzaPlayer","food,dad jokes"],
["My backpack's dream job is to carry the team.","BackpackBuddy","kids,work"],
["Why did the broom get promoted? It swept the competition.","SweepySteve","work,dad jokes"],
["I told the dentist a joke and he cracked up.","DentistDan","doctors,dad jokes"],
["Why was the belt arrested? For holding up pants.","FashionCop","dad jokes"],
["I ate a clock yesterday. It was time-consuming.","ClockEater","dad jokes"],
["Why don't fish play basketball? They're afraid of the net.","FishCoach","animals,sports"],
["What's the difference between an outlaw and an in-law? Outlaws are wanted.","LawJokeLarry","marriage,dad jokes"],
["What do you get if you cross a snake and a pie? A python.","SnakeBaker","animals,food"],
["Why did the scarecrow get a raise? He was outstanding at his job.","ScarecrowSam","work,dad jokes"],
["What do you call a bear with no socks? Barefoot.","BareBear","animals,kids"],
["Why did the bicycle need a nap? It was two-tired.","TiredBike","sports,dad jokes"],
["A book just fell on my head. I only have my shelf to blame.","BookBonk","school,dad jokes"],
["Velcro. What a rip off.","VelcroVince","dad jokes"],
["What did one plate say to another? Lunch is on me.","PlatePal","food,dad jokes"],
["I'm terrified of elevators. I'm going to start taking steps to avoid them.","ElevatorEd","dad jokes"],
["RIP boiling water. You will be mist.","BoilingBob","food,science"],
["The shovel was a ground-breaking invention.","InventorIvan","science,dad jokes"],
["Two guys walked into a bar. The third one ducked.","BarBuddy","dad jokes"],
["I know a lot of jokes about retired people. None of them work.","RetiredRon","work,dad jokes"],
["What did the pirate say on his 80th birthday? Aye matey.","PiratePete","kids,dad jokes"],
["Justice is a dish best served cold. If it were served warm, it would be justwater.","JusticeJoke","dad jokes"],
["I don't trust people who do acupuncture. They're back stabbers.","NeedleNed","doctors,dad jokes"],
["A man walks into a library and asks for books about paranoia. The librarian whispers: They're right behind you.","ParanoidPaul","school,dad jokes"],
["Why did the bullet end up losing his job? He got fired.","BulletBob","work,dad jokes"],
["Why do pigs never share secrets? Because they're always squealing.","PiggyPete","animals,kids"],
["How do you make an octopus laugh? With ten-tickles.","OctopusOllie","animals,kids"],
["What do you call a line of men waiting to get haircuts? A barber-queue.","BarberBob","dad jokes"],
["Why are computers so smart? They listen to their motherboard.","SmartPC","programming,dad jokes"],
["I used to be a personal trainer, then I gave my too weak notice.","WeakWalt","sports,work"],
["The rotation of Earth really makes my day.","SpinningSam","science,dad jokes"],
["What's the most terrifying word in nuclear physics? Oops.","NuclearNerd","science,dad jokes"],
["How do astronomers organize a party? They planet.","AstroParty","science,kids"],
["I was wondering why the frisbee was getting bigger. Then it hit me.","FrisbeePhil","sports,dad jokes"],
["What do you call an unpredictable camera? A loose Canon.","PhotoPaul","dad jokes"],
["Why did the old man fall in the well? Because he couldn't see that well.","WellWilly","dad jokes"],
["What do you call a magician who lost his magic? Ian.","MagicIan","dad jokes"],
["Why did Adele cross the road? To say hello from the other side.","MusicMark","dad jokes"],
["I hate when people say age is only a number. Age is clearly a word.","WordNerdWill","dad jokes"],
["What's the best time to go to the dentist? Tooth-hurty.","DentalDave","doctors,dad jokes"],
["My wife accused me of being immature. I told her to get out of my fort.","FortFred","marriage,kids"],
["Why did the invisible man turn down the job offer? He couldn't see himself doing it.","GhostWorker","work,dad jokes"],
["Why do crabs never give to charity? Because they're shellfish.","CrabbyCarl","animals,dad jokes"],
["If at first you don't succeed, skydiving is not for you.","SkydiverSteve","sports,dad jokes"],
["I went to a seafood disco last week. I pulled a mussel.","DiscoFish","food,sports"],
["Two antennas met on a roof, fell in love, and got married. The ceremony wasn't much, but the reception was excellent.","AntennaAl","dad jokes,marriage"],
["I told my cat a joke. He wasn't amewsed.","CatComic","animals,dad jokes"],
["I just found out I'm colorblind. The news came completely out of the purple.","ColorCarl","dad jokes"],
["What do you call a pony with a cough? A little horse.","PonyDoc","animals,doctors"],
["Whoever invented zero really made something out of nothing.","ZeroHero","science,dad jokes"],
["How do you know when a joke becomes a dad joke? When the punchline becomes apparent.","MetaJokeMike","dad jokes"],
["I child-proofed my house but somehow they still get in.","ParentPeter","kids,dad jokes"],
["Why was the strawberry crying? Because its parents were in a jam.","JamKid","food,kids"],
["What did the left eye say to the right eye? Between us, something smells.","EyeDoc","doctors,dad jokes"],
["I'm so good at sleeping, I can do it with my eyes closed.","SleepMaster","dad jokes"],
["How do you make holy water? You boil the hell out of it.","HolyHarry","dad jokes"],
["I used to run a dating service for chickens. But I was struggling to make hens meet.","ChickenMatch","animals,marriage"],
["Singing in the shower is fun until you get soap in your mouth. Then it's a soap opera.","ShowerSinger","dad jokes"],
["My grandfather has the heart of a lion and a lifetime ban from the zoo.","LionGrandpa","animals,dad jokes"],
["I told my wife she should embrace her mistakes. She hugged me.","HugHarry","marriage,dad jokes"],
["What do you call a can opener that doesn't work? A can't opener.","OpenerOllie","dad jokes"],
["Did you hear about the claustrophobic astronaut? He just needed a little more space.","SpaceMan","science,dad jokes"],
["Why don't mummies take vacations? They're afraid they'll relax and unwind.","MummyVacay","kids,dad jokes"],
["A woman in labor suddenly shouted: Shouldn't! Wouldn't! Couldn't! Didn't! Can't! Don't won't! The doctor said: Don't worry, those are just contractions.","GrammarDoc","doctors,school"],
["What happens when you go to the bathroom in France? European.","FrenchJoke","dad jokes"],
["What did the buffalo say when his kid left for college? Bison.","BuffaloDad","animals,school"],
["Why did the nurse need a red pen? In case she needed to draw blood.","NurseJoke","doctors,dad jokes"],
["What do you call a bee that can't make up its mind? A maybe.","IndecisiveBee","animals,dad jokes"],
["I'm reading a horror story in braille. Something bad is about to happen. I can feel it.","BrailleReader","dad jokes"],
["What do you call a dinosaur that crashes its car? Tyrannosaurus wrecks.","WreckedRex","animals,kids"],
["Where do you learn to make ice cream? Sunday school.","IceCreamIvan","food,school"],
["What's a pirate's favorite letter? You'd think it's R but his first love was the C.","PiratePun","kids,dad jokes"],
["Why do seals swim in salt water? Because pepper water makes them sneeze.","SealSally","animals,kids"],
["What do you call a shoe made of banana? A slipper.","SlipperSteve","food,dad jokes"],
["How does Moses make his coffee? Hebrews it.","BiblicalBrew","food,dad jokes"],
["Want to hear a joke about paper? Never mind, it's tearable.","TearableTim","dad jokes"],
["What sits at the bottom of the sea and twitches? A nervous wreck.","SeaFloorSam","dad jokes"],
["I'm no cheetah. You're lion.","ZooZack","animals,dad jokes"],
["Why did the stadium get hot after the game? All the fans left.","HotStadium","sports,dad jokes"],
["What do you give a sick lemon? Lemon-aid.","LemonDoc","food,doctors"],
["What does a clock do when it's hungry? It goes back four seconds.","HungryHour","food,dad jokes"],
["I used to work at a shoe factory. It was sole destroying.","ShoeWorker","work,dad jokes"],
["I bought a ceiling fan the other day. Complete waste of money. He just stands there applauding and saying: Ooh, I love how smooth it is.","CeilingFan","dad jokes"],
["What do you call a hippie's wife? Mississippi.","HippieHal","marriage,dad jokes"],
["Why did the gym close down? It just didn't work out.","GymOwner","sports,work"],
["What gets wetter the more it dries? A towel.","TowelTina","kids,dad jokes"],
["I ordered a chicken and an egg from Amazon. I'll let you know.","AmazonAlex","food,dad jokes"],
["What does a baby computer call its father? Data.","BabyByte","programming,kids"],
["Why did the PowerPoint cross the road? To get to the other slide.","SlideShow","programming,work"],
["What do sprinters eat before a race? Nothing, they fast.","SprintSnack","sports,food"],
["What do you call a careful wolf? Aware wolf.","WolfWill","animals,dad jokes"],
["I broke my finger last week. On the other hand, I'm okay.","BrokenFinger","doctors,dad jokes"],
["How do you tell the difference between a bull and a cow? It is either one or the udder.","CowJoke","animals,dad jokes"],
["A man with authority walks into a bar. He orders everyone a round.","AuthorityAl","dad jokes"],
["Why did the student eat his test? Because his teacher said it was a piece of cake.","TestEater","school,food"],
["What did one hat say to the other? Stay here, I'm going on ahead.","HatHarry","dad jokes"],
["Why can't a nose be 12 inches long? Because then it'd be a foot.","NoseFred","doctors,dad jokes"],
["Why did the music teacher go to jail? Because she got caught with a sharp object.","SharpTeacher","school,dad jokes"],
["What has four wheels and flies? A garbage truck.","GarbageGuy","kids,dad jokes"],
["My dog sat on a piece of sandpaper. He said it was a bit ruff.","RuffDog","animals,dad jokes"],
["What do you call a sleeping T-Rex? A dino-snore.","SnoringRex","animals,kids"],
["I tried to write with a broken pencil but it was pointless.","BrokenPen","school,dad jokes"],
["What do elves learn in school? The elf-abet.","ElfStudent","kids,school"],
["Why do cows have hooves instead of feet? Because they lactose.","LactoseJoke","animals,science"],
["I got fired from the candle factory because I refused to work wick-ends.","CandleWorker","work,dad jokes"],
["What type of music are balloons scared of? Pop music.","BalloonBob","kids,dad jokes"],
["Why was the big cat disqualified from the race? Because it was a cheetah.","RaceCheetah","animals,sports"],
["How do you catch a squirrel? Climb a tree and act like a nut.","SquirrelSam","animals,kids"],
["What did the stamp say to the envelope? Stick with me and we'll go places.","StampSteve","dad jokes"],
["Why did the kid throw his clock out the window? He wanted to see time fly.","TimeFly","kids,dad jokes"],
["What do you call a sleeping pizza? A piZZZa.","SleepyPizza","food,kids"],
["If April showers bring May flowers, what do May flowers bring? Pilgrims.","HistoryHelen","school,kids"],
["Why do bees hum? Because they don't know the words.","HummingBee","animals,kids"],
["Why was the baby ant confused? Because all its uncles were ants.","AntKid","animals,kids"],
["What do you call a deer with no eyes? No idea.","DeerDave","animals,dad jokes"],
["Why couldn't the bicycle stand up by itself? It was two tired.","TiredBicycle","sports,dad jokes"],
["What did the ocean say to the shore? Nothing, it just waved.","WavingOcean","dad jokes"],
["Why don't some fish play piano? You can't tuna fish.","TunaPlayer","animals,food"],
["What kind of car does an egg drive? A Yolkswagen.","EggDriver","food,dad jokes"],
["How do you make a tissue dance? You put a little boogie in it.","DancingTissue","kids,dad jokes"],
["What do you call a cow with a twitch? Beef jerky.","JerkyCow","animals,food"],
["Why don't blondes make good pharmacists? They can't get the bottles in the typewriter.","PharmPhil","doctors,dad jokes"],
["I made a pencil with two erasers. It was pointless.","DoublEraser","school,dad jokes"],
["What do you call a potato wearing glasses? A spec-tater.","PotatoPete","food,dad jokes"],
["What's a teacher's favorite nation? Expla-nation.","NationTeacher","school,dad jokes"],
["Why couldn't the sesame seed leave the casino? He was on a roll.","CasinoSeed","food,dad jokes"],
["What do you call a snowman in the summer? A puddle.","PuddlePete","kids,dad jokes"],
["Whiteboards are remarkable.","MarkerMark","school,dad jokes"],
["I have a photographic memory but I always forget to bring the film.","MemoryMike","dad jokes"],
["I'd tell you a joke about pizza, but it's a bit too saucy.","SaucySteve","food,dad jokes"],
["Why don't eggs tell each other jokes? They crack each other up.","EggComedian","food,dad jokes"],
["I asked a librarian if she had books on paranoia. She whispered: They're right behind you.","LibraryLarry","school,dad jokes"],
["Why did the golfer wear two pairs of pants? In case he got a hole in one.","GolfPants","sports,dad jokes"],
["What do clouds wear under their shorts? Thunderpants.","CloudKid","kids,science"],
["How do you fix a broken tuba? With a tuba glue.","MusicFixer","school,dad jokes"],
["I tried to take a photograph of fog. I mist.","FogSnapper","dad jokes"],
["I asked the boss if I could leave early. He said only if I make up the time. So I said: Sure, it's twenty past fourteen.","TimeTrick","work,dad jokes"],
["What do cows listen to? Moo-sic.","MusicCow","animals,kids"],
["What do snowmen eat for breakfast? Frosted Flakes.","SnowBreakfast","food,kids"],
["A steak pun is a rare medium well done.","SteakPun","food,dad jokes"],
["I would make a belt out of watches but it would be a waist of time.","WatchBelt","dad jokes"],
["Why did the computer go to the doctor? Because it had a virus.","SickPC","programming,doctors"],
["What concert costs only 45 cents? 50 Cent featuring Nickelback.","ConcertCarl","dad jokes"],
["My wife is on a tropical food diet. The house is full of stuff. It's enough to make a mango crazy.","MangoMike","food,marriage"],
["What do you call a factory that sells good products? A satis-factory.","FactoryFun","work,dad jokes"],
["How do mountains stay warm? They wear snow caps.","MountainMike","science,kids"],
["What do you call a magic dog? A Labracadabrador.","MagicDog","animals,kids"],
["Why was the sand wet? Because the sea weed.","SeaWeedSam","kids,dad jokes"],
["What did the traffic light say to the car? Don't look! I'm about to change.","TrafficJoke","dad jokes"],
["Why do melons have weddings? Because they cantaloupe.","MelonMarriage","food,marriage"],
["How do you get a country girl's attention? A tractor.","FarmerJoke","dad jokes"],
["I called the tinnitus helpline. It just kept ringing.","RingRing","doctors,dad jokes"],
["I'm addicted to brake fluid, but I can stop anytime.","BrakeFluidBob","dad jokes"],
["I just flew in from New York and boy are my arms tired.","FlyingFred","dad jokes"],
["What did the janitor say when he jumped out of the supply closet? Supplies!","SupplySurprise","work,kids"],
["What do you call a bee born in May? A maybe.","MayBee","animals,kids"],
["If the early bird gets the worm, I'll sleep in until there's pancakes.","PancakePete","food,dad jokes"],
["What do you get when you put a vest on an alligator? An investigator.","InvestiGator","animals,dad jokes"],
["What do you call birds that stick together? Vel-crows.","VelcrowBird","animals,dad jokes"],
["Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them.","NegativeNerd","science,school"],
["How do you make a squid laugh? Give it ten-tickles.","SquidTickle","animals,kids"],
["I went to the zoo and there was only one dog. It was a shih tzu.","ZooDog","animals,dad jokes"],
["What did the big flower say to the little flower? Hey there, bud!","FlowerFred","kids,dad jokes"],
["Why can't you hear a pterodactyl going to the bathroom? Because the P is silent.","DinoQuiet","animals,science"],
["I once had a dream I was floating in an ocean of orange soda. It was more of a Fanta sea.","FantaFred","food,dad jokes"],
["What do you call a lazy baby kangaroo? A pouch potato.","LazyJoey","animals,kids"],
["I couldn't figure out how to put my seatbelt on. Then it clicked.","SeatbeltSam","dad jokes"],
["A perfectionist walked into a bar. Apparently the bar wasn't set high enough.","PerfectPat","dad jokes"],
["What do dentists call their X-rays? Tooth pics.","DentistDave","doctors,dad jokes"],
["What kind of exercise do lazy people do? Diddly squats.","LazyLou","sports,dad jokes"],
["What do you call a toothless bear? A gummy bear.","ToothlessTed","animals,kids"],
["I sold my vacuum the other day. All it was doing was collecting dust.","VacuumSeller","dad jokes"],
["Why was six scared of seven? Because seven eight nine.","NumberNancy","kids,dad jokes"],
["Where do pirates get their hooks? Second hand stores.","PirateShop","kids,dad jokes"],
["How much space will be freed in the EU after Brexit? Approximately 1 GB.","BrexitByte","programming,dad jokes"],
["I've just been diagnosed as colorblind. I know, it really came out of the purple.","ColorBlindCarl","doctors,dad jokes"],
["What do you call a dinosaur that knows a lot of words? A thesaurus.","DinoWords","animals,school"],
["Why couldn't the pirate learn the alphabet? He was always lost at C.","PirateAlphabet","kids,school"],
["If money doesn't grow on trees, why do banks have branches?","BankBranch","work,dad jokes"],
["How do you stop a bull from charging? Cancel its credit card.","BullStop","animals,dad jokes"],
];

async function run() {
  let ok = 0, skip = 0, err = 0;
  console.log("🫙 Seeding " + J.length + " jokes directly to database...\n");
  
  for (let i = 0; i < J.length; i++) {
    const [text, author, tagsStr] = J[i];
    const tagNames = tagsStr.split(",").map(t => t.trim());
    
    try {
      // Skip duplicates
      const existing = await prisma.joke.findFirst({ where: { text } });
      if (existing) { skip++; continue; }
      
      // Upsert tags
      const tagRecords = await Promise.all(
        tagNames.map(n => prisma.tag.upsert({ where: { name: n }, create: { name: n }, update: {} }))
      );
      
      await prisma.joke.create({
        data: {
          text, author, lang: "EN", status: "approved",
          approvedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000), // Random time in last 7 days
          tags: { create: tagRecords.map(t => ({ tagId: t.id })) },
        },
      });
      ok++;
      if (ok % 25 === 0) console.log("  ✅ " + ok + " jokes added...");
    } catch (e) {
      err++;
    }
  }
  
  console.log("\n🎉 Done! " + ok + " added, " + skip + " skipped (duplicates), " + err + " errors.");
  await prisma.$disconnect();
}

run();
