export const LANGUAGES = [
  { code: "ALL", flag: "🌐", name: "All Languages" },
  { code: "EN", flag: "🇬🇧", name: "English" },
  { code: "RO", flag: "🇷🇴", name: "Română" },
  { code: "DE", flag: "🇩🇪", name: "Deutsch" },
  { code: "FR", flag: "🇫🇷", name: "Français" },
  { code: "ES", flag: "🇪🇸", name: "Español" },
  { code: "PT", flag: "🇵🇹", name: "Português" },
  { code: "IT", flag: "🇮🇹", name: "Italiano" },
  { code: "BG", flag: "🇧🇬", name: "Български" },
  { code: "HU", flag: "🇭🇺", name: "Magyar" },
  { code: "SV", flag: "🇸🇪", name: "Svenska" },
  { code: "NL", flag: "🇳🇱", name: "Nederlands" },
  { code: "PL", flag: "🇵🇱", name: "Polski" },
  { code: "RU", flag: "🇷🇺", name: "Русский" },
  { code: "UK", flag: "🇺🇦", name: "Українська" },
  { code: "CS", flag: "🇨🇿", name: "Čeština" },
  { code: "SK", flag: "🇸🇰", name: "Slovenčina" },
  { code: "HR", flag: "🇭🇷", name: "Hrvatski" },
  { code: "SR", flag: "🇷🇸", name: "Српски" },
  { code: "SL", flag: "🇸🇮", name: "Slovenščina" },
  { code: "EL", flag: "🇬🇷", name: "Ελληνικά" },
  { code: "TR", flag: "🇹🇷", name: "Türkçe" },
  { code: "AR", flag: "🇸🇦", name: "العربية" },
  { code: "HE", flag: "🇮🇱", name: "עברית" },
  { code: "FA", flag: "🇮🇷", name: "فارسی" },
  { code: "HI", flag: "🇮🇳", name: "हिन्दी" },
  { code: "BN", flag: "🇧🇩", name: "বাংলা" },
  { code: "TA", flag: "🇱🇰", name: "தமிழ்" },
  { code: "TH", flag: "🇹🇭", name: "ไทย" },
  { code: "VI", flag: "🇻🇳", name: "Tiếng Việt" },
  { code: "ZH", flag: "🇨🇳", name: "中文" },
  { code: "JA", flag: "🇯🇵", name: "日本語" },
  { code: "KO", flag: "🇰🇷", name: "한국어" },
  { code: "MS", flag: "🇲🇾", name: "Bahasa Melayu" },
  { code: "ID", flag: "🇮🇩", name: "Bahasa Indonesia" },
  { code: "FI", flag: "🇫🇮", name: "Suomi" },
  { code: "DA", flag: "🇩🇰", name: "Dansk" },
  { code: "NO", flag: "🇳🇴", name: "Norsk" },
  { code: "IS", flag: "🇮🇸", name: "Íslenska" },
  { code: "ET", flag: "🇪🇪", name: "Eesti" },
  { code: "LV", flag: "🇱🇻", name: "Latviešu" },
  { code: "LT", flag: "🇱🇹", name: "Lietuvių" },
  { code: "GA", flag: "🇮🇪", name: "Gaeilge" },
  { code: "CY", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", name: "Cymraeg" },
  { code: "CA", flag: "🇪🇸", name: "Català" },
  { code: "GL", flag: "🇪🇸", name: "Galego" },
  { code: "EU", flag: "🇪🇸", name: "Euskara" },
  { code: "AF", flag: "🇿🇦", name: "Afrikaans" },
  { code: "SW", flag: "🇰🇪", name: "Kiswahili" },
  { code: "TL", flag: "🇵🇭", name: "Tagalog" },
  { code: "KA", flag: "🇬🇪", name: "ქართული" },
  { code: "HY", flag: "🇦🇲", name: "Հայերեն" },
  { code: "AZ", flag: "🇦🇿", name: "Azərbaycan" },
  { code: "UZ", flag: "🇺🇿", name: "Oʻzbek" },
  { code: "KK", flag: "🇰🇿", name: "Қазақ" },
  { code: "MN", flag: "🇲🇳", name: "Монгол" },
  { code: "NE", flag: "🇳🇵", name: "नेपाली" },
  { code: "SI", flag: "🇱🇰", name: "සිංහල" },
  { code: "MY", flag: "🇲🇲", name: "မြန်မာ" },
  { code: "KM", flag: "🇰🇭", name: "ខ្មែរ" },
  { code: "LO", flag: "🇱🇦", name: "ລາວ" },
  { code: "AM", flag: "🇪🇹", name: "አማርኛ" },
  { code: "HA", flag: "🇳🇬", name: "Hausa" },
  { code: "YO", flag: "🇳🇬", name: "Yorùbá" },
  { code: "IG", flag: "🇳🇬", name: "Igbo" },
  { code: "MK", flag: "🇲🇰", name: "Македонски" },
  { code: "SQ", flag: "🇦🇱", name: "Shqip" },
  { code: "BS", flag: "🇧🇦", name: "Bosanski" },
  { code: "MT", flag: "🇲🇹", name: "Malti" },
  { code: "LB", flag: "🇱🇺", name: "Lëtzebuergesch" },
];

export const EMOJIS = ["😂", "🤣", "😐", "🙄", "💀"];

export const FLAG_REASONS = [
  { key: "inappropriate", label: "Inappropriate content" },
  { key: "offensive", label: "Offensive / Hate speech" },
  { key: "spam", label: "Spam / Advertisement" },
  { key: "duplicate", label: "Duplicate joke" },
  { key: "other", label: "Other" },
];
